# Generated by Django 5.1 on 2024-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juguetes',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_fabricacion', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(max_length=20)),
                ('clasificacion', models.CharField(max_length=20)),
            ],
        ),
    ]
